// src/lib/components/toggles/index.svelte
<script lang="ts">
  import * as ButtonGroup from "$lib/components/ui/button-group/index.js";
  import ThemeToggle from "$lib/components/toggles/theme-toggle.svelte";
  import LanguageToggle from "$lib/components/toggles/language-toggle.svelte";
</script>

<ButtonGroup.Root
  orientation="vertical"
  aria-label="Toggles"
  class="fixed top-4 right-5 cursor-pointer h-fit"
>
  <ThemeToggle />
  <LanguageToggle />
</ButtonGroup.Root>

// app/components/toggles/index.tsx
import { ButtonGroup } from "@/components/ui/button-group";

import ThemeToggle from "./theme-toggle";
import LanguageToggle from "./language-toggle";

export function Toggles() {
  return (
    <ButtonGroup
      orientation="vertical"
      aria-label="Toggles"
      className="fixed top-4 right-5 cursor-pointer h-fit"
    >
      <ThemeToggle />
      <LanguageToggle />
    </ButtonGroup>
  );
}

export default Toggles;
