// resources/assets/js/components/index/programming/GithubEvent.vue
<template>
    <div class="github-event">
        <octicon v-bind:label="eventMessage()" scale="2">
            <icon name="circle" scale="2"></icon>
            <octicon v-bind:name="eventIcon()" class="octicon-icon"></octicon>
        </octicon>
        <div class="github-content">
            <h4>
                <a v-bind:href="`https://github.com/${ghEvent.repo.name}`" v-bind:title="`View ${ghEvent.repo.name} on Github`">
                    {{ ghEvent.repo.name }}
                </a>
            </h4>
            <p>
                {{ eventMessage() }}
                <small v-if="ghEvent.payload.issue"> <a v-bind:href="ghEvent.payload.issue.html_url">View issue</a></small>
            </p>
            <ul class="github-commits" v-if="ghEvent.payload.commits">
                <li v-for="commit in ghEvent.payload.commits" v-bind:key="commit.sha">
                    <span className="octicon octicon-git-commit"></span>
                    {{ commit.message }}
                    <small><a v-bind:href="`https://github.com/${ghEvent.repo.name}/commit/${commit.sha}`" title="View Commit">View Commit</a></small>
                </li>
            </ul>
            <p class="relative-time"><small>{{ relativeTimeCreated() }}</small></p>
        </div>
    </div>
</template>

<script>
    import distanceInWordsToNow from 'date-fns/distance_in_words_to_now';

    import Icon from 'vue-awesome/components/Icon';
    import 'vue-awesome/icons/circle';

    import Octicon from 'vue-octicon/components/Octicon.vue';
    import 'vue-octicon/icons/comment';
    import 'vue-octicon/icons/eye';
    import 'vue-octicon/icons/git-branch';
    import 'vue-octicon/icons/git-pull-request';
    import 'vue-octicon/icons/issue-closed';
    import 'vue-octicon/icons/issue-opened';
    import 'vue-octicon/icons/issue-reopened';
    import 'vue-octicon/icons/organization';
    import 'vue-octicon/icons/repo';
    import 'vue-octicon/icons/repo-push';
    import 'vue-octicon/icons/rocket';
    import 'vue-octicon/icons/star';
    import 'vue-octicon/icons/tag';
    import 'vue-octicon/icons/trashcan';

    export default {
        name: 'github-event',
        props: [
            'gh-event',
        ],
        components: {
            Octicon,
            Icon,
        },
        data() {
            return {
                eventIcon() {
                    if (this.ghEvent.type === 'PushEvent') {
                        return 'repo-push';
                    } else if (this.ghEvent.type === 'IssueCommentEvent') {
                        return 'comment';
                    } else if (this.ghEvent.type === 'DeleteEvent') {
                        return 'trashcan';
                    } else if (this.ghEvent.type === 'WatchEvent') {
                        if (this.ghEvent.payload.action === 'watched') {
                            return 'eye';
                        } else if (this.ghEvent.payload.action === 'started') {
                            return 'star';
                        }
                    } else if (this.ghEvent.type === 'IssuesEvent') {
                        if (this.ghEvent.payload.action === 'opened') {
                            return 'issue-opened';
                        } else if (this.ghEvent.payload.action === 'reopened') {
                            return 'issue-reopened';
                        } else if (this.ghEvent.payload.action === 'closed') {
                            return 'issue-closed';
                        }
                    } else if (this.ghEvent.type === 'CreateEvent') {
                        if (this.ghEvent.payload.ref_type === 'tag') {
                            return 'tag';
                        } else if (this.ghEvent.payload.ref_type === 'branch') {
                            return 'git-branch';
                        } else if (this.ghEvent.payload.ref_type === 'repository') {
                            return 'repo';
                        }
                    } else if (this.ghEvent.type === 'MemberEvent') {
                        if (this.ghEvent.payload.action === 'added') {
                            return 'organization';
                        }
                    } else if (this.ghEvent.type === 'PublicEvent') {
                        return 'rocket';
                    } else if (this.ghEvent.type === 'PullRequestEvent') {
                        return 'git-pull-request';
                    }
                    // else {
                    //     console.log(this.ghEvent.type); // eslint-disable-line
                    // }
                },
                eventMessage() {
                    if (this.ghEvent.type === 'PushEvent') {
                        return 'Pushed to repo';
                    } else if (this.ghEvent.type === 'IssueCommentEvent') {
                        return `Commented on Issue #${this.ghEvent.payload.issue.number}`;
                    } else if (this.ghEvent.type === 'DeleteEvent') {
                        return 'Deleted';
                    } else if (this.ghEvent.type === 'WatchEvent') {
                        if (this.ghEvent.payload.action === 'watched') {
                            return 'Watched repo';
                        } else if (this.ghEvent.payload.action === 'started') {
                            return 'Stared repo';
                        }
                    } else if (this.ghEvent.type === 'IssuesEvent') {
                        if (this.ghEvent.payload.action === 'opened') {
                            return `Opened issue #${this.ghEvent.payload.issue.number}`;
                        } else if (this.ghEvent.payload.action === 'reopened') {
                            return `Reopened issue #${this.ghEvent.payload.issue.number}`;
                        } else if (this.ghEvent.payload.action === 'closed') {
                            return `Closed issue #${this.ghEvent.payload.issue.number}`;
                        }
                    } else if (this.ghEvent.type === 'CreateEvent') {
                        if (this.ghEvent.payload.ref_type === 'tag') {
                            return 'Tagged repo';
                        } else if (this.ghEvent.payload.ref_type === 'branch') {
                            return `Created Branch ${this.ghEvent.payload.ref}`;
                        } else if (this.ghEvent.payload.ref_type === 'repository') {
                            return `Created ${this.ghEvent.payload.ref_type}`;
                        }
                    } else if (this.ghEvent.type === 'MemberEvent') {
                        if (this.ghEvent.payload.action === 'added') {
                            return 'Added collaborator';
                        }
                    } else if (this.ghEvent.type === 'PublicEvent') {
                        return 'Made Public';
                    } else if (this.ghEvent.type === 'PullRequestEvent') {
                        return 'Pull Request';
                    }
                },
                relativeTimeCreated() {
                    const relativeTime = distanceInWordsToNow(this.ghEvent.created_at, {
                        includeSeconds: true,
                        addSuffix: true,
                    });
                    return relativeTime;
                },
            }
        },
    }
</script>

<style scoped>
    .octicon {
        display: block;
        margin: 0 auto;
    }
    .octicon-icon {
        fill: #333;
    }

    p {
        margin: 5px 0;
    }

    .github-content h4 {
        margin-bottom: 0;
    }

    .relative-time {
        margin: 0;
    }
</style>

// src/components/Code/GithubEvent.jsx
import React from 'react';
import moment from 'moment';

const propTypes = {
	data: React.PropTypes.object.isRequired,
};

function GithubEvent({ data }) {
	const relativeTimeCreated = moment(data.created_at).fromNow();

	let eventType = '';
	let eventMessage = '';
	if (data.type === 'PushEvent') {
		eventType = 'octicon-repo-push';
		eventMessage = 'Pushed to repo';
	} else if (data.type === 'IssueCommentEvent') {
		eventType = 'octicon-comment';
		eventMessage = 'Commented on Issue';
	} else if (data.type === 'DeleteEvent') {
		eventType = 'octicon-trashcan';
		eventMessage = 'Deleted';
	} else if (data.type === 'WatchEvent') {
		if (data.payload.action === 'watched') {
			eventType = 'octicon-eye';
			eventMessage = 'Watched repo';
		} else if (data.payload.action === 'started') {
			eventType = 'octicon-star';
			eventMessage = 'Stared repo';
		}
	} else if (data.type === 'IssuesEvent') {
		if (data.payload.action === 'opened') {
			eventType = 'octicon-issue-opened';
			eventMessage = 'Opened issue';
		} else if (data.payload.action === 'reopened') {
			eventType = 'octicon-issue-reopened';
			eventMessage = 'Reopened issue';
		} else if (data.payload.action === 'closed') {
			eventType = 'octicon-issue-closed';
			eventMessage = 'Closed issue';
		}
	} else if (data.type === 'CreateEvent') {
		if (data.payload.ref_type === 'tag') {
			eventType = 'octicon-tag';
			eventMessage = 'Tagged repo';
		}
	} else if (data.type === 'MemberEvent') {
		if (data.payload.action === 'added') {
			eventType = 'octicon-organization';
			eventMessage = 'Added collaborator';
		}
	} else if (data.type === 'PublicEvent') {
		eventType = 'octicon-rocket';
		eventMessage = 'Made Public';
	} else if (data.type === 'PullRequestEvent') {
		eventType = 'octicon-git-pull-request';
		eventMessage = 'Pull Request';
	} else {
		console.log(data.type); // eslint-disable-line
	}

	let Commits;
	if (typeof data.payload.commits !== 'undefined') {
		Commits = data.payload.commits.map((commit, i) => (
			<li key={i}>
				<span className="octicon octicon-git-commit"></span>
				{ commit.message }
				<small><a href={ commit.url } title="View Commit">View Commit</a></small>
			</li>
		));
	}

	return (
		<div>
			<div className="github-type">
				<span className="fa-stack fa-3x">
					<i className="fa fa-circle fa-lg"></i>
					<span className={`mega-octicon ${eventType}`}></span>
				</span>
			</div>
			<div className="github-content">
				<h4>
					<a href={ data.repo.url } title="View Repo">
						{ data.repo.name }
					</a>
				</h4>
				<p>{ eventMessage }</p>
				<ul className="github-commits">{ Commits }</ul>
				<p><small>{ relativeTimeCreated }</small></p>
			</div>
		</div>
	);
}

GithubEvent.propTypes = propTypes;

export default GithubEvent;
